### PR TITLE
fixes #82 - 'NameError: global name 'instance' is not defined'

### LINKED ISSUE #82: E   NameError: global name 'instance' is not defined
the error is produced in [ddf.py:380](https://github.com/paulocheque/django-dynamic-fixture/blob/master/django_dynamic_fixture/ddf.py#L380)

`getattr(instance, field.name).save(django_file.name, django_file, save=False)`

should be

`getattr(__instance, __field.name).save(django_file.name, django_file, save=False)`

### PR DESCRIPTION
**Pull request by saxix**

### CODE REVIEW

**Comment by paulocheque** [comment]
amazing!

**Comment by vtemian** [comment]
This fix is not yet released. Can you kindly make a new release? It would help some people. Thanks!

**Comment by paulocheque** [comment]
Released: 1.9.1

Sorry for the delay and thanks for remember!

**Comment by vtemian** [comment]
Thank you!

**Pull request merged**
