### PR TITLE
Django 1.9 support

### PR DESCRIPTION
**Pull request by gregmuellegger**
Adding support for Django 1.9.

Django 1.9 released yesterday. It would be nice if DDF could support it, however slight changes are required. Here is a patch to make the test suite run against Django 1.9

### CODE REVIEW

**Comment by paulocheque** [comment]
Amazing!

But the tests failed, could you trying fixing them? So I can merge your full PR?

**Comment by gregmuellegger** [comment]
Oops, should be fixed now. Let's wait for the tests to complete.

**Comment by paulocheque** [comment]
Great! Amazing!

**Comment by gregmuellegger** [comment]
Hey, is it possible to create a new release including the Django 1.9 support?

**Comment by paulocheque** [comment]
Released! Thanks a lot for the PR and sorry for the delay!

**Comment by gregmuellegger** [comment]
Awesome!

**Pull request merged**
